---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "homeloan123"
  namespace: "default"
  labels:
    app: "homeloan123"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "homeloan123"
  template:
    metadata:
      labels:
        app: "homeloan123"
    spec:
      containers:
      - name: "homeloandr-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/pranalipol3/homeloandr@sha256:c316fa8dbbbab18208f68cefff7eeb1864d72df08862338a035b54db2857de24"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "homeloan123-hpa-aoi4"
  namespace: "default"
  labels:
    app: "homeloan123"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "homeloan123"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
